version: '3'

services:
  app:
    image: 'restaurant-springboot:latest'
    build: .
    container_name: restaurant-management-api
    ports:
      - '8000:8000'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      BE_PORT: 8000
    depends_on:
      - db

  db:
    image: 'postgres:16.1-alpine'
    restart: always
    environment:
      POSTGRES_DB: 'restaurant_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '@3563949Zx'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: