server:
  port: ${BE_PORT:8001}

logging:
  file:
    path: log
  level:
    root: info
  pattern:
    level: 'user:%X{user} %5p'

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/restaurant_db
    username: 'postgres'
    password: '@3563949Zx'
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'
